#!/bin/python3

import math
import os
import random
import re
import sys



if __name__ == '__main__':
    n = int(input())

i = 1
while i <= 10:
    result = i * n
    print(str(n)+" x "+str(i)+" = "+str(result))
    i += 1

    
